export const skillList = [
  {
    skillTitle: 'Tool',
    skillName: [
      'Adobe Illustrator',
      'Adobe Photoshop',
      'Adobe Premiere',
      'Adobe Dimension',
      'Adobe XD',
      'Adobe Audition',
      'Figma',
      'Git・Github',
      'Docker',
      'Visual Studio Code',
      'Google Analytics',
      'Google Tag Manager',
      'Google Search Console',
      'Microsoft Clarity',
      'Ubersuggest',
      'Logic pro X',
      'Blender',
      'Jw_CAD',
    ],
  },
  {
    skillTitle: 'Coding',
    skillName: ['HTML・CSS・SCSS', 'Javascript', 'PHP'],
  },
  {
    skillTitle: 'Framework / Library / CMS',
    skillName: [
      'React・Next.js',
      'vue・Nuxt.js',
      'webpack',
      'Vite',
      'Astro',
      'GSAP',
      'Three.js / React Three Fiber',
      'jQuery',
      'Framer motion',
      'tailwindcss',
      'Bootstrap',
      'Wordpress',
      'wp-env',
      'Concrete CMS',
    ],
  },
];
